### PR TITLE
Re-enabling Windows tests

### LINKED ISSUE #106: Windows doesn't support colons in filenames
This makes several of our tests fail, because they try to create folders such as `localhost:8001` in the local cache.

Example failure:

```
Failed to copy file [D:\Jenkins\workspace\ignition_fuel-tools-ci-pr_any-windows7-amd64\ws\ign-fuel-tools\build\test_cache\localhost:8007\alice\models\My Model\2\model.config] to [D:\Jenkins\workspace\ignition_fuel-tools-ci-pr_any-windows7-amd64\ws\ign-fuel-tools\build\test_cache\localhost:8007\alice\models\My Model\3\model.config]: The filename, directory name, or volume label syntax is incorrect.
```

We could just change the tests, but this would also be a problem for a user who actually needs a port number in their servers. This will also be a problem for model names containing colons.

So for now I'll disable these tests on Windows until we come up with a better solution.

### LINKED ISSUE #231: Failing Windows CI tests on main branch
We have two consistently failing tests in Windows CI on the `main` branch:

Example: https://build.osrfoundation.org/job/ign_fuel-tools-pr-win/112/

[FuelClientTest.CachedModel](https://build.osrfoundation.org/job/ign_fuel-tools-pr-win/112/testReport/junit/(root)/FuelClientTest/CachedModel/)
[LocalCacheTest.AllModels](https://build.osrfoundation.org/job/ign_fuel-tools-pr-win/112/testReport/junit/(root)/LocalCacheTest/AllModels/)

-----

### FuelClientTest.CachedModel

https://github.com/ignitionrobotics/ign-fuel-tools/blob/c47d85f00419d4a684f1955e56fb4404a060f77d/src/FuelClient_TEST.cc#L617-L625

```
[ RUN      ] FuelClientTest.CachedModel
5: [36m[Dbg] [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc:48] [m[36mCreating local model in [[m[36mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\build\ignition-fuel_tools8[m[36m][m[36m
5: [m[33m[Wrn] [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\LocalCache.cc:105] [m[33mServer directory does not exist [[m[33mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\build\ignition-fuel_tools8\test_cache\fuel.ignitionrobotics.org[m[33m]
5: [mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc(621): error: Value of: result
5:   Actual: false
5: Expected: true
5: C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc(622): error: Expected equality of these values:
5:   ResultType::FETCH_ALREADY_EXISTS
5:     Which is: 4-byte object <05-00 00-00>
5:   result.Type()
5:     Which is: 4-byte object <07-00 00-00>
5: C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc(624): error: Expected equality of these values:
5:   common::joinPaths(common::cwd(), "test_cache", "localhost:8007", "alice", "models", "My Model", "3")
5:     Which is: "C:\\Jenkins\\workspace\\ign_fuel-tools-pr-win\\ws\\build\\ignition-fuel_tools8\\test_cache\\localhost8007\\alice\\models\\My Model\\3"
5:   path
5:     Which is: ""
```

### LocalCacheTest.AllModels

https://github.com/ignitionrobotics/ign-fuel-tools/blob/c47d85f00419d4a684f1955e56fb4404a060f77d/src/LocalCache_TEST.cc#L248-L258

```15: [ RUN      ] LocalCacheTest.AllModels
15: [36m[Dbg] [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\LocalCache_TEST.cc:47] [m[36mCreating 6 local models in [[m[36mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\build\ignition-fuel_tools8[m[36m][m[36m
15: [m[36m[Dbg] [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\LocalCache_TEST.cc:99] [m[36mCreating 3 local models in [[m[36mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\build\ignition-fuel_tools8[m[36m][m[36m
15: [m[33m[Wrn] [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\LocalCache.cc:105] [m[33mServer directory does not exist [[m[33mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\build\ignition-fuel_tools8\test_cache\fuel.ignitionrobotics.org[m[33m]
15: [mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\LocalCache_TEST.cc(258): error: Expected: (uniqueNames.end()) != (uniqueNames.find( "http://localhost:8001/alice/models/am1")), actual: 8-byte object <50-F6 94-ED 10-02 00-00> vs 8-byte object <50-F6 94-ED 10-02 00-00>
15: [  FAILED  ] LocalCacheTest.AllModels (45 ms)```

### PR DESCRIPTION
**Pull request by mjcarroll**
Fix tests around Windows' handling (or not handling) of `:` and `@` in filesystem paths.

To address this, I did a few things.

1) If a URI has an authority (that is a username or a port in the format `username@host:port`), then we URL encode that to get a "safe" path.

2) Make sure that we are passing `hasAuthority = true` for all of our URIs that use `https`.  This may be a behavior that we want to change in gz-common eventually, but is sufficient for here.

3) Fixes `UniqueName` to generate valid paths for both `ModelIdentifier` and `WorldIdentifier`.  I also choose to make `UniqueName` always return unix-delimited paths, which cleans up some windows-specific test logic.

I believe that this resolves the test failures in `FuelClientTest.CachedWorld` and `FuelClientTest.PatchModelFail` as described in #373.

When forward ported to `main`, this should resolve #231

This (finally) resolves #106

### CODE REVIEW

File: src/FuelClient.cc [hunk 1]
```diff
@@ -1425,8 +1443,7 @@ Result FuelClient::DownloadModel(const common::URI &_modelUrl,
   }
 
   _path = gz::common::joinPaths(this->Config().CacheLocation(),
-      id.Server().Url().Path().Str(), id.Owner(), "models", id.Name(),
-      id.VersionStr());
+      id.UniqueName(), id.VersionStr());
```
Comment (azeey) [inline src/FuelClient.cc:1446]: I noticed that `UniqueName` uses `Server().Url().Str()`, while the code here previously had `Server().Url().Path().Str()`. Is this intentional?

**Review by azeey — APPROVED** [review]
LGTM! Just a couple of questions.

Also, have you seen https://github.com/gazebosim/gz-common/issues/38? I'm wondering if we did proper encoding in gz-common, we wouldn't need some of the changes in this PR.

File: src/FuelClient.cc (hunk 1 above)
Comment (mjcarroll) [reply src/FuelClient.cc:1446]: This is because previously when we had a web URL, we weren't setting the authority and treating the whole thing as a path, when really the domain name is the authority in this case

```
# Before (authority = false)
https://fuel.gazebosim.com/user/model
  Authority: ""
  Path: "fuel.gazebosim.com/user/model"

https://foo@localhost:8080/user/model -> 
  Authority: ""
  Path: "foo@localhost:8080/user/model"

# After (authority = true)
https://fuel.gazebosim.com/user/model
  Authority: "fuel.gazebosim.com"
  Path: "user/model"

https://foo@localhost:8080/user/model -> 
  Authority: "foo@localhost:8080"
  Path: "user/model"
```

So we need the "full" URL returned by `Url()` to get the Authority as part of the unique name.

File: include/gz/fuel_tools/FuelClient.hh [hunk 2]
```diff
@@ -315,6 +315,13 @@ namespace gz
                   const std::vector<WorldIdentifier> &_ids,
                   size_t _jobs = 2);
 
+      /// \brief Check if a model is already present in the local cache.
+      /// \param[in] _id The model identifier
+      /// \param[out] _path Local path where the model can be found.
+      /// \return FETCH_ERROR if not cached, FETCH_ALREADY_EXISTS if cached.
+      public: Result CachedModel(const ModelIdentifier &_id,
```
[the remark this answers is not in the document]
Comment (mjcarroll) [reply include/gz/fuel_tools/FuelClient.hh:322]: It wasn't covered by existing tests, so I probably didn't notice it.  I suppose it's unnecessary without `include`-ing in SDF.

File: src/FuelClient.cc (hunk 1 above)
Comment (azeey) [reply src/FuelClient.cc:1446]: Ah, I misunderstood `Path` as a function that somehow converts the URL into a file path, not returning the formal `Path`  of a URL. This makes sense. Thanks!

**Comment by azeey** [comment]
> Additionally, with bumping gz-common, it may be that we can just fix it there and most of this goes away in a forward port to main?

Okay, I've added to the list of things to consider working on for Ionic. I think this is good to merge!
